ffmpeg -re -i ~/transcoder-testing/test-with-timer.flv -f flv -c:v copy -c:a aac -strict -2 -maxrate 4M rtmp://127.0.0.1/live/dlivetestdlivetestdlivetestdlive_dlivetest-1 &
ffmpeg -re -i ~/transcoder-testing/test-with-timer.flv -f flv -c:v copy -c:a aac -strict -2 -maxrate 4M rtmp://127.0.0.1/live/dlivetestdlivetestdlivetestdlive_dlivetest-2 &
ffmpeg -re -i ~/transcoder-testing/test-with-timer.flv -f flv -c:v copy -c:a aac -strict -2 -maxrate 4M rtmp://127.0.0.1/live/dlivetestdlivetestdlivetestdlive_dlivetest-3 &
ffmpeg -re -i ~/transcoder-testing/test-with-timer.flv -f flv -c:v copy -c:a aac -strict -2 -maxrate 4M rtmp://127.0.0.1/live/dlivetestdlivetestdlivetestdlive_dlivetest-4 &
ffmpeg -re -i ~/transcoder-testing/test-with-timer.flv -f flv -c:v copy -c:a aac -strict -2 -maxrate 4M rtmp://127.0.0.1/live/dlivetestdlivetestdlivetestdlive_dlivetest-5 &
ffmpeg -re -i ~/transcoder-testing/test-with-timer.flv -f flv -c:v copy -c:a aac -strict -2 -maxrate 4M rtmp://127.0.0.1/live/dlivetestdlivetestdlivetestdlive_dlivetest-6 &
ffmpeg -re -i ~/transcoder-testing/test-with-timer.flv -f flv -c:v copy -c:a aac -strict -2 -maxrate 4M rtmp://127.0.0.1/live/dlivetestdlivetestdlivetestdlive_dlivetest-7 &
ffmpeg -re -i ~/transcoder-testing/test-with-timer.flv -f flv -c:v copy -c:a aac -strict -2 -maxrate 4M rtmp://127.0.0.1/live/dlivetestdlivetestdlivetestdlive_dlivetest-8 &
ffmpeg -re -i ~/transcoder-testing/test-with-timer.flv -f flv -c:v copy -c:a aac -strict -2 -maxrate 4M rtmp://127.0.0.1/live/dlivetestdlivetestdlivetestdlive_dlivetest-9 &
ffmpeg -re -i ~/transcoder-testing/test-with-timer.flv -f flv -c:v copy -c:a aac -strict -2 -maxrate 4M rtmp://127.0.0.1/live/dlivetestdlivetestdlivetestdlive_dlivetest-10 &
