ffplay -i rtmp://127.0.0.1/live/dlivetestdlivetestdlivetestdlive_dlivetest-1 &
ffplay -i rtmp://127.0.0.1/live/dlivetestdlivetestdlivetestdlive_dlivetest-2 &
ffplay -i rtmp://127.0.0.1/live/dlivetestdlivetestdlivetestdlive_dlivetest-3 &
ffplay -i rtmp://127.0.0.1/live/dlivetestdlivetestdlivetestdlive_dlivetest-4 &
ffplay -i rtmp://127.0.0.1/live/dlivetestdlivetestdlivetestdlive_dlivetest-5 &
ffplay -i rtmp://127.0.0.1/live/dlivetestdlivetestdlivetestdlive_dlivetest-6 &
ffplay -i rtmp://127.0.0.1/live/dlivetestdlivetestdlivetestdlive_dlivetest-7 &
ffplay -i rtmp://127.0.0.1/live/dlivetestdlivetestdlivetestdlive_dlivetest-8 &
ffplay -i rtmp://127.0.0.1/live/dlivetestdlivetestdlivetestdlive_dlivetest-9 &
ffplay -i rtmp://127.0.0.1/live/dlivetestdlivetestdlivetestdlive_dlivetest-10 &
